### ISSUE TITLE
交个朋友

### ISSUE THREAD

**Issue by xckevin** [luckybilly/luckybilly.github.io#1]
hi，
    之前通过简历渠道了解过你，没有把握住错失了人才。从blog github等都找不到你的联系方式，不知是否有兴趣聊聊？

**Comment by luckybilly** [comment]
@xckevin hi, 欢迎加我QQ： 532493721

**Comment by xckevin** [comment]
真实难为了，已经不用QQ了😂 。微信ok不，我的微信_ID： xckevin927 @luckybilly
